apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: 'springboot-app'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['springboot-service:80']
