apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082   # Can be any free port between 30000–32767
